[package]
name = "dialect-interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = { workspace = true }
tree-sitter = { workspace = true }

[dev-dependencies]
tree-sitter-java = "0.20.2"