name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Lint
        run: cargo clippy
      - name: Build
        run: cargo build --verbose --all
      - name: Test
        run: cargo test --verbose --all
      - name: Security Audit
        run: cargo audit --deny=warnings
