name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Format
        run: cargo fmt --all --message-format=human --check
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - name: Build
        run: cargo build --all
      - name: Test
        run: cargo test --all
      - name: Security Audit
        run: cargo audit --deny=warnings
